### PR TITLE
Add support for additonal test apks.

### LINKED ISSUE #67: Add support `additional-app-test-apks`
See https://github.com/TestArmada/flank/pull/542 for more information.

### PR DESCRIPTION
**Pull request by runningcode**
Fixes #67

### CODE REVIEW

**Comment by charlesdurham** [comment]
I think the common use case is a single app apk and then multiple test apks. Flank supports this by only requiring a single app apk and using that as the fallback if its omitted w/ later test apks. Might be nice to carry that functionality over here.

**Comment by runningcode** [comment]
@charlesdurham hey, that's a great idea. can you help me structure the DSL to support this use case?
one way would be like
listOf("- app: app", "test: test.apk", "test: test2.apk"), its a bit more verbose than the current, but it might work better. what do you think?

**Comment by charlesdurham** [comment]
Yeah it gets kind of messy and I can't think of anything great, maybe it's just better as-is.

The only thing I could think of was making the pair `Pair<String?, String>` instead. But then passing null is almost the same as repeating the path to the app apk 🤷‍♂.

**Comment by runningcode** [comment]
I was also just thinking of having the whole thing be a string?

**Comment by charlesdurham** [comment]
Up to you 😄 `List<Pair<String, List<String>>` could also work where the first string is the app apk and the list of strings are the test apks.

**Comment by alosdev** [comment]
@runningcode will it be merged one day?

**Pull request closed without merging**
